### ISSUE TITLE
VADJ no use?

### ISSUE THREAD

**Issue by cederom** [grandideastudio/jtagulator#11]
Hey Joe =) What is the purpose of VADJ input when I have to select VCC for JTAG port manually and VADJ needs to be disconnected? Some future use?

**Comment by joegrand** [comment]
VADJ is the output from the PWM/op amp hardware on the JTAGulator that's used to create the target system voltage and drive the on-board level translators. It's nice to have accessible on the channel pins for testing to make sure the target system voltage is being generated corrected and thought it might be nice to have for future use (but don't have any particular ideas in mind). If you connect VADJ to a target, it could load down the voltage output and affect the results from the JTAGulator.

**Comment by cederom** [comment]
ah so its the output not the input.. on KT-LINK multi-purpose interface there is a VADJ input so you can connect to target VCC and voltage shifters will do the job with setting VCC :-)
