### ISSUE TITLE
Feature request: SWD & cJTAG detection

### ISSUE THREAD

**Issue by ikarus23** [grandideastudio/jtagulator#15]
Hi! First of all: Thanks for this awesome tool!
I was wondering if it is possible to implement a SWD and cJTAG detection/mapping feature?

**Comment by joegrand** [comment]
Glad you like the tool! Yes, it's certainly possible to implement SWD and cJTAG. It's on the TO DO list (https://github.com/grandideastudio/jtagulator/blob/master/TODO.markdown), but I can't promise if/when I'll be able to get to it :)

**Comment by ikarus23** [comment]
Oh, sorry for not checking the TODO list first.
...And sorry for not checking the closed issues.

No worries, I know how it is. A lot of things would be easier if the day had 48 hours. ;)

**Comment by joegrand** [comment]
SWD added in v1.7 (https://github.com/grandideastudio/jtagulator/releases/tag/1.7)

See PR #30 for limitations particularly related to the JTAGulator hardware front-end and incompatibility with many SWD-based systems due to their pull resistors.
