### ISSUE TITLE
Level-shifting in Jtagulator

### ISSUE THREAD

**Issue by bl4ckic3** [grandideastudio/jtagulator#17]
Hi, I am not sure if it is right to open a new issue about this, but is there any workaround or document on making compatible level-shifter for 5V devices in JTagulator?

**Comment by joegrand** [comment]
This has been on the [TO DO](https://github.com/grandideastudio/jtagulator/blob/master/TODO.markdown) for a while, but no progress has been made. It might be possible to create a plug-in board to sit on top of the male header pins with a 5V-compatible bi-directional level shifter (GTL2003 or MAX3000E) or replace the existing level translators/VADJ circuitry with something that supports a wider voltage range. I don't have any date of when I'll get around to experimenting with that, though.
