### ISSUE TITLE
How to deal with pull up/downs?

### ISSUE THREAD

**Issue by 0ff** [grandideastudio/jtagulator#21]
Hi Joe,

thanks for your great tool, really liking the idea and I've also enjoyed the talks you gave about it!
Now unfortunately I've run into a problem actually finding a JTAG port: The JTAGulator seems to have problems driving some pins, as they are pulled up/down on the target.

See this image I captured with a logic analyser both in digital and analog domain:
![jtagulator_connected_idscan](https://user-images.githubusercontent.com/1755213/42129555-fc1e88ba-7cc7-11e8-869c-6c12b09f339d.png)
As you can see, Channels 0, 2 and 3 are working just fine.
But 1 and 4-6 don't - the JTAGulator isn't able to drive the pins I guess?

The JTAGulator itself is working fine, if I disconnect every pin from the target, this is what I expected and got:
![jtagulator_unconnected_idscan](https://user-images.githubusercontent.com/1755213/42129563-52217f60-7cc8-11e8-9c67-1821197273e3.png)

This is the pins I'm trying to connect to, unfortunately I'm missing the EE background to actually know what happens, yet I guess there are too strong pull up/downs on the board?
![channels_resistors](https://user-images.githubusercontent.com/1755213/42129566-7e7d0e9e-7cc8-11e8-90a4-d119ca9da3d8.jpg)

Pin|Gnd|Vdd
---|---|---
0|nc|nc
1|48k1|46k6
2|nc|nc
3|47k2|48k6
4|50k3|48k7
5|nc|nc
6|47k|48k2

I choose these pins purely based on their physical position on the board (datasheet for the CPU) and the fact that they are also broken out somewhere else on the board on a connector. So while I'm *rather* sure this should be JTAG in some form, I don't know for sure.
I did test an eval board with the same CPU and JTAGulating it worked right at the first try - so it's really the board that's making problems here.

I would appreciate any input you have and thanks again for your great tool!

**Comment by joegrand** [comment]
Hi there- Those pull resistor values are not common for JTAG. Looking at the data sheet for the AT91M55800A (http://ww1.microchip.com/downloads/en/DeviceDoc/doc1745.pdf) shows that JTAG *is* supported, but the same pins are shared with ICE (In-Circuit Emulation), which is not JTAG-compliant and the JTAGulator wouldn't be able to detect that mode. The JTAGSEL pin is used to select (see page 8 of the data sheet). Also on that same page, the JTAG pins have internal pull-ups, so it's another clue that the test points you've connected to are not the right ones (or at least not configured for JTAG). The grouping also looks odd to me, so try to see if there are another grouping of test points with some set of traces all going in the same direction.

In the event that you do detect the correct pins, the data sheet states that the chip has no Device ID. So, your only way to discover would be to use the BYPASS Scan command (not IDCODE Scan). 

The JTAGulator should work with targets that have pull-ups larger (weaker) than 1k, but that's not of concern here. The data sheet doesn't state what the internal values are, but they're probably more like 10k. Your particular target chip also has an NTRST pin, which must be held high to ensure the JTAG TAP isn't asynchronously reset (this is done by the JTAGulator during JTAGulation).
