### ISSUE TITLE
JTAGulator interfaced with a Raspberry Pi

### ISSUE THREAD

**Issue by CyberTecky** [grandideastudio/jtagulator#26]
Greetings,

I'm still new to the JTAGulator but if I understand its design and functionality am I correct by assuming that the JTAGulator is only capable of handling lower-level communication, and if I wanted to interface and utilize higher-level communication/functions then would I need to use other dev boards such as, the Bus Pirate, TIAO USB Multi-Protocol Adapter (TUMPA), etc.?  That being said, can a Raspberry Pi 3+ B Model be used for that purpose, to act as the adapter/interface?

At this point, it is possible that I've caused the reader to start scratching their head in confusion while trying to figure out what exactly I'm wanted to accomplish, so as a JTAGulator newbie I'll try to be a bit more specific.  That being said, I'd like to do things such as, a) unbricking routers, b) basic reverse engineering of old embedded hardware (e.g., routers, smartphones, and misc IoT devices.

Overall, I see so many products out there that advertise capability and functionality for JTAG, UART, I2C, SPI, Serial communications, but the how-to's and instructions seem limited and/or a bit of a challenge to research through a clear path that might answer most if not all of my questions.  Anyway, I'm definitely excited to begin this adventure now that I have the JTAGulator, but I would be most grateful for those out there with experience in hardware hacking/reverse engineering to steer me in the right direction - specifically in the open-source direction, if possible.

Thanks again,

CJ

**Comment by joegrand** [comment]
No responses, so I'm closing the issue.
