### ISSUE TITLE
TRST pin Question

### ISSUE THREAD

**Issue by yum7777** [grandideastudio/jtagulator#43]
Hi!

Should it be connected to the "TRST" pin while running the jtagulator?

When I turn on the power and use a multimeter to analyze the TRST pin of my target, it always stays at "0V".

Thanks!

**Comment by joegrand** [comment]
TRST is an optional pin per the JTAG specification and is not required to be connected to the JTAGulator (though if you do, the JTAG scan commands will try to identify it). It is an active LOW signal. If you're measuring LOW, something on your target board may be holding the system in reset. The JTAGulator sets all unused channels to HIGH, so it's possible that connecting the pin to the JTAGulator may bring the device out of reset. The JTAGulator also gives you the option for certain commands to bring the unused channels LOW in between scans to force an asynchronous system reset.
