### ISSUE TITLE
change "buspirate port" to " buspirate_port" in wiki

### ISSUE THREAD

**Issue by kocoman1** [grandideastudio/jtagulator#49]
In https://github.com/grandideastudio/jtagulator/wiki/OpenOCD

openocd -f interface/buspirate.cfg -c "transport select jtag; buspirate port <port>" -f <target>

 "buspirate port" to " buspirate_port"

thx

**Comment by joegrand** [comment]
The documentation is correct. 

As of OpenOCD commit [8399cb](https://sourceforge.net/p/openocd/code/ci/8399cbc9584985c2b9e4aafb3a6afdb17df89b7f/) on August 14, 2021, the group adapter commands have been changed, including from "buspirate_port" to "buspirate port"

While "buspirate_port" will still work with newer releases of OpenOCD, it has been deprecated and it is unknown when it will stop working. Hence the change to the current, correct format.
