### ISSUE TITLE
Basic User Doc

### ISSUE THREAD

**Issue by RenegadeTech** [grandideastudio/jtagulator#5]
I have recently obtained a jtagulator and I am looking to use,
the information about how to get started and what is needed is all over the place, given a youtube video or hand written documentation. 
A basic how to start and interface with the jtagulator would be nice.

**Comment by joegrand** [comment]
A quick start guide is already available from https://www.parallax.com/downloads/jtagulator-product-brief <https://www.parallax.com/downloads/jtagulator-product-brief>. I'd recommend taking a look at that along with the videos on updating the firmware (https://www.youtube.com/watch?v=xlXwy-weG1M <https://www.youtube.com/watch?v=xlXwy-weG1M>, always grab the latest release version from github) and the extended introduction (https://www.youtube.com/watch?v=GgMOBhmEJXA <https://www.youtube.com/watch?v=GgMOBhmEJXA>).

I'm planning to create a more inclusive user's manual in the future, but the above should give you everything you need to get started. Links to all relevant documentation and resources will always be accessible from www.grandideastudio.com/portfolio/jtagulator/ <http://www.grandideastudio.com/portfolio/jtagulator/> 

Joe
