### ISSUE TITLE
Firmware starting after 1.8 is not working on our jtagulator from parallax

### ISSUE THREAD

**Issue by dummys** [grandideastudio/jtagulator#53]
Hi,
I have a problem with firmware after 1.8. It is not working. There is no communication from the UART. How to debug this ?
Iam using version 1.3.2 from your website to flash it and I get no error.
Version of board is: SMT094648-0087 32115 Rev. B.
PS: I also tried to flash the version that I compiled myself using the Top option, same problem. 1.8 works but not higher

**Comment by joegrand** [comment]
Please see the [FAQ](https://github.com/grandideastudio/jtagulator/wiki/Frequently-Asked-Questions) question 6 and closed issue #40. It's likely related to the EEPROM having other data in it that caused the JTAGulator to start up in an alternate mode (new features added on 1.8 and above). 

If that doesn't solve your problem, please provide more details as mentioned in the FAQ question 8.

**Comment by dummys** [comment]
OMG you are right. Thanks for explanation.
