### ISSUE TITLE
Scans aborting by default without waiting for the spacebar or any other key

### ISSUE THREAD

**Issue by ramyapandian1987** [grandideastudio/jtagulator#54]
Kindly help us to resolve the issue. Details are as follows - 

JTAGulator firmware version – 1.10
Description of the target hardware – Linux Raspberrypi 5.10.63-v7l+ armv7l GNU/LINUX
Connections/Wiring - 
![image](https://user-images.githubusercontent.com/37421836/158618220-9b381d53-eae3-4917-b594-46b8cf3e42df.png)
![image](https://user-images.githubusercontent.com/37421836/158618365-05574366-be6e-4bbf-a5f6-c053b8c38267.png)
Below is the IDCODE scan output for jtag option -
![image](https://user-images.githubusercontent.com/37421836/158619063-b0a9e173-f31c-4153-a41b-d11188b50a3b.png)
Below is the BYPASS scan output for jtag option -
![image](https://user-images.githubusercontent.com/37421836/158619345-adbda88a-355f-45db-a30f-d89fa9ed4232.png)
•	Operating system details – macOS Monterey Version 12.2.1
•	Version numbers of any accompanying software – CoolTerm version 1.9.1
•	What steps you have already taken to troubleshoot/debug the issue
Updated settings on Raspberry Pi 4 (Target) – as mentioned in [http://www.grandideastudio.com/wp-content/uploads/jtagulator_rpi_demo_notes.pdf](https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.grandideastudio.com%2Fwp-content%2Fuploads%2Fjtagulator_rpi_demo_notes.pdf&data=04%7C01%7Caaligombe%40towson.edu%7C855fb9a0b9e148c0978f08da06e01555%7Ccbf9739249f649dda8a619f710efcc35%7C0%7C0%7C637829857781002714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z65WEPuMvmwh0%2F%2F7kpW8JjMaVmXZq%2BwVsU2WV%2Fq96fU%3D&reserved=0)
 
1.	enable_jtag_gpio = 1
2.	enable_uart = 1
3.	Removed quiet from cmdline.txt
4. gpio=22-27=np

**Comment by joegrand** [comment]
Thanks for the detailed report.

It's likely that the terminal program is sending both a CR and a LF, which is causing the JTAGulator to interpret it as two separate key presses. Please check your CoolTerm settings as shown below - you'll want to ensure that it's *only* sending a CR.

<img width="1108" alt="Screen Shot 2022-03-16 at 8 34 00 AM" src="https://user-images.githubusercontent.com/4250259/158628431-9ca1a947-a149-4ded-a3d4-a7611c679094.png">

**Comment by ramyapandian1987** [comment]
Thank you very much for the quick response! Really appreciate it.

It is working fine now. Have a great day!

**Comment by ramyapandian1987** [comment]
Hello Sir,

I am trying to dump the memory of my RaspberryPi 4 through Jtagulator and OpenOCD. However, I am facing the following issue - 

<img width="1422" alt="Screen Shot 2022-04-05 at 1 45 55 PM" src="https://user-images.githubusercontent.com/37421836/161818332-a0b781de-bc92-471d-9d0d-bf9617d6ba9d.png">

Attached is the raspberrypi 4 config file that I use - 
[raspi4_config.txt](https://github.com/grandideastudio/jtagulator/files/8420718/raspi4_config.txt)


I am reopening this issue because the details of my hardwares remain the same as mentioned above.

Kindly help us resolve this issue.

Thanks!

**Comment by joegrand** [comment]
This is a different issue that has to do with your host configuration, not with the JTAGulator functionality. Please see the [OpenOCD section of the Wiki](https://github.com/grandideastudio/jtagulator/wiki/OpenOCD) and closed issue #51. We aren't able to help with individual implementations like this.

**Comment by joegrand** [comment]
A video demonstration of the OpenOCD functionality can be found [here](https://www.youtube.com/watch?v=NWTNH1RgUZc&t=1331s).
