### ISSUE TITLE
JTAGulator light stays red even after flashing new eeprom, no serial output

### ISSUE THREAD

**Issue by joshterrill** [grandideastudio/jtagulator#57]
I got my jtagulator and have been trying to play around with it. I plug it in, and the light goes from yellow to solid red and stays there. I read online that I probably should flash the firmware onto it, so I went here: https://github.com/grandideastudio/jtagulator/releases/tag/1.11 and downloaded the propeller tools/IDE in a Parallels Windows 10 VM (I'm using MacOS). I plugged the device in, the VM picked it up, I set the baud rating correctly in the serial devices section of Windows. I opened up the eeprom file, PropellerTools opened up, loaded the ROM, everything seemed fine, the lights on the JTAGulator started blinking, but then they go back to red and stay there. 

From within the Windows VM, I don't get any serial output on COM3, and when I try from the host MacOS using `screen /dev/tty.usbserial-AB0P6L9O 115200` I also don't get anything. I try pressing reset, and it goes through the same cycle of yellow light, then solid red, nothing on the screen.

I just ordered another one from adafruit in case it's just a faulty chip. But thought I'd check here first in case there's a fix I could try.

Edit: I've also tried several different cables to rule out a possible cable issue.

**Comment by joegrand** [comment]
Please see [FAQ](https://github.com/grandideastudio/jtagulator/wiki/Frequently-Asked-Questions) item 6 ("When the JTAGulator powers up, the LED turns YELLOW and then RED. There's nothing displayed in the terminal program and it appears unresponsive."). 

If this doesn't solve the problem, you can reopen the issue.
