### ISSUE TITLE
GPIO.W producing weird voltage

### ISSUE THREAD

**Issue by STMRabbit** [grandideastudio/jtagulator#59]
Hello Joe,  
I am testing my Jtagulator, and it got weird performance in GPIO.W  
>Set GPIO.W to ``CH23..CH0: 00000000 00000000 00000000  (0x000000)`` , all channels behave normally, 0.03V  
>Set GPIO.W to ``CH23..CH0: 11111111 11111111 11111111  (0xFFFFFF)``  , I got CH0 to CH7 at only 2.77V and others at normally 3.27V   

So i was suspecting if U7/U8/U9 or R11 were blown, but It's not likely, since  

>Set GPIO.W to ``CH23..CH0: 00000000 00000000 00001111  (0x00000F)`` , CH0-CH7 became normally 3.27V

So it looks really like some power supply issues, but the weird thing is that 

>Set GPIO.W to ``CH23..CH0: 00000000 00000000 11111111  (0x0000FF)`` , CH0-CH7 became only 2.77V again

So I'm really confused, would you mind give me some tips about it? Thx a lot! Changing host/USB port/USB cable/operating system/serial terminal doesn't seem helps.   

### Environment
Jtagulator clone Rev. B with 1.10 and 1.11

Thx!

**Comment by joegrand** [comment]
Please see the [FAQ](https://github.com/grandideastudio/jtagulator/wiki/Frequently-Asked-Questions) # 9. If the board is indeed a clone and not official, you'll be better off asking in my [Discord server](https://discord.com/invite/wud8KnF2Gm) where others might be able to help.

It sounds like a hardware issue, so I'd double check all of your connections, especially between the Propeller, level translators, and series resistor arrays. Make sure the components are actually good, and the PCB was fabricated properly.
