### ISSUE TITLE
is there any way to debug why uart passthrough is not outputting when doing tx rx connected together test(for echo test)?

### ISSUE THREAD

**Issue by kocoman1** [grandideastudio/jtagulator#61]
is there any way to debug why uart passthrough is not outputting when doing tx rx connected together test(for echo test)? thx

**Comment by joegrand** [comment]
Have you enabled Local Echo when you started the passthrough command?

https://github.com/grandideastudio/jtagulator/blob/master/JTAGulator.spin#L1996

**Comment by joegrand** [comment]
<img width="1208" alt="Screen Shot 2023-04-15 at 6 21 53 PM" src="https://user-images.githubusercontent.com/4250259/232261076-78bf196a-525a-474a-91ee-c3c103082e15.png">

**Comment by joegrand** [comment]
No response from OP, assuming the issue was solved.

**Comment by kocoman1** [comment]
sorry I didn't have time to look at it till now..

Its giving me a▒aaa▒aa
its receiving ▒, should i need some logic probe to debug it? what chip is broken do you think? thanks

**Comment by joegrand** [comment]
Are you using an officially manufactured JTAGulator or are you building your own? You can try to follow the [test procedure](http://www.grandideastudio.com/wp-content/uploads/jtagulator_testproc.pdf) to see if that narrows down the problem. Though, if you're able to properly communicate with the JTAGulator, it's likely not UART hardware related. Without knowing anything about your setup, hardware, baud rate you're testing with, etc., I'm really not able to give you any specific suggestions.
