### ISSUE TITLE
jtagulator locked

### ISSUE THREAD

**Issue by VraiHack** [grandideastudio/jtagulator#65]
Hi Joe,
Few days ago i got my first "Jtagulator" from Mouser Electronics , and i was doing my first simple Demo to test its functionality by targeting an [Elbert V2 - Spartan 3A FPGA](https://numato.com/docs/elbert-v2-spartan-3a-fpga-development-board/).

since i already know the JTAG ports of the Target Board (already tagged), i only used connected to the Jtagulator the 4 essential pins (TCK, TMS, TDO and TDI), and ground. And the Jtagulator was capable to identify them only for the TMS wasn't (TMS = N/A)
![IMG_20230824_110728](https://github.com/grandideastudio/jtagulator/assets/26716241/d585f80d-303a-4ce9-bd78-7b96756f2f97)

And the target output voltage is 3.3 on the JTAG pin (i measured and also that mentioned in the product description of the target board : https://numato.com/docs/elbert-v2-spartan-3a-fpga-development-board/)

while i am recording the demo to my instagram page for my fans, to show them how i was capable to identify the JTAG pins using Jtagulator, i noticed that the LED status turned and maintain  in RED color (no heat on the board), and minicom connection shows "device loked".
![image](https://github.com/grandideastudio/jtagulator/assets/26716241/e208ca80-dc90-4c15-8a32-40fc7392014f)

The weird thing is that, i still capable to see the Jtagulator in my driver list in both windows and Linux machine, but no output appear on the terminal. 
![image](https://github.com/grandideastudio/jtagulator/assets/26716241/0c369afd-aa97-4f2b-9d8e-339957df954f)

Actual status :
By re-plugging the Jtagulator, for a nano seconds the LED trun to Green then remain RED.
I pressed the Reset button, problem remain always the same.
![IMG_20230824_111418](https://github.com/grandideastudio/jtagulator/assets/26716241/6e9000d4-2949-4b66-9f72-33ae51550c69)

**_What do you suggest on me in my troubleshooting ? or no chance for me :(_**

**Jtagulator board information:**
#32215 Rev B
2013 by 3.0 US
SMT 117291-0135
Thanks

**Comment by joegrand** [comment]
Please see [FAQ](https://github.com/grandideastudio/jtagulator/wiki/Frequently-Asked-Questions) item 6. It's possible that the JTAGulator is in the OpenOCD or Logic Analyzer modes. 

If the device isn't detected by minicom, it could also be a port/access issue. Try unplugging the JTAGulator and using it on a different machine to compare the results.

**Comment by VraiHack** [comment]
Thanks Joe, we still learning from you :), by following this my problem solved: 
![image](https://github.com/grandideastudio/jtagulator/assets/26716241/5194e451-4874-473a-8f61-7e328887d554)

**Comment by VraiHack** [comment]
Problem solved by following FAQ https://github.com/grandideastudio/jtagulator/wiki/Frequently-Asked-Questions
