### ISSUE TITLE
is there some schemaitcs I can look to repair my UART issue? thx  https://github.com/grandideastudio/jtagulator/issues/61

### ISSUE THREAD

**Issue by kocoman1** [grandideastudio/jtagulator#66]
is there some schemaitcs I can look to repair my UART issue? thx

https://github.com/grandideastudio/jtagulator/issues/61

**Comment by joegrand** [comment]
See [FAQ](https://github.com/grandideastudio/jtagulator/wiki/Frequently-Asked-Questions) question 1. Specifically, the hardware resources are [here](http://www.grandideastudio.com/portfolio/jtagulator/).
