### ISSUE TITLE
Unable to update to latest version

### ISSUE THREAD

**Issue by camsmithsdev8090** [grandideastudio/jtagulator#69]
I'm trying to update my Jtagulator to the latest firmware using the Propeller Tool and get the following error when trying to flash the eeprom for versions above v1.11 (was able to get from v1.2.2 to v1.10 successfully): Error: Communication stalled due to system problem.

If someone can please assist that would be greatly appreciated

**Comment by joegrand** [comment]
Can you look at https://github.com/grandideastudio/jtagulator?tab=readme-ov-file#firmware and also provide more details, screenshots, photos, etc.?

**Comment by joegrand** [comment]
Issue closed due to no response.
