### ISSUE TITLE
Cant load firmware 1.12 on JTAGulator

### ISSUE THREAD

**Issue by yooo1999** [grandideastudio/jtagulator#71]
I read [that](https://github.com/grandideastudio/jtagulator/issues/46) but it does not help me.

I tried to update jtagulator (32115)  from 1.6 to 1.12 in Windows

I tried  Propeller 1.3.2

When I load EEPROM  (c:\Users\USER\Downloads\jtagulator-1.12\JTAGulator.eeprom )and press "Load EEPROM" I got

Propeller chip lost on COM8

![image](https://github.com/user-attachments/assets/93d8adc2-4ec3-424a-a26d-1ade03b7ed1c)
![image](https://github.com/user-attachments/assets/364541e5-4f30-40a6-b464-6791ce3e6f27)

**Comment by joegrand** [comment]
https://forums.parallax.com/discussion/97251/hardware-communication-error-fixed
https://forums.parallax.com/discussion/170359/propeller-lost-on-com-port

You could also try using one of the alternative development environments: 
https://github.com/grandideastudio/jtagulator?tab=readme-ov-file#firmware

**Comment by bigttys0** [comment]
I sincerely appreciate Joe's dedication to the Jtagulator repo. This is the only repo I subscribe to and every time I break out the Jtagulator I know Joe is always there on the other end to assist. Thanks, Joe!

**Comment by yooo1999** [comment]
I have tried
![image](https://github.com/user-attachments/assets/7141b26c-1e0d-487f-8a2f-19a2f513012c)
Latency 16 and 12 and same error

**Comment by joegrand** [comment]
They have posted the same issue on my [Discord](https://discord.com/invite/wud8KnF2Gm) and have yet to provide the information requested in [FAQ](https://github.com/grandideastudio/jtagulator/wiki/Frequently-Asked-Questions) item 10 though I've asked multiple times. It's too hard to help debug without knowing about their specific JTAGulator hardware, computer/OS environment, etc.

**Comment by joegrand** [comment]
No response from OP.
